# Generated by Django 4.2.23 on 2025-07-21 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nova Conversa', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuário'), ('assistente', 'Assistente')], max_length=20)),
                ('conteudo', models.TextField()),
                ('e_biblico', models.BooleanField(default=True)),
                ('citacoes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('rejeitado', 'Rejeitado'), ('erro', 'Erro')], default='processando', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chatbot_biblico.sessaochat')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['criado_em'],
            },
        ),
    ]
